In [ ]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
import re
import nltk
from nltk.corpus import  stopwords
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [48]:
nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('stopwords')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\manis\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\manis\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\manis\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [49]:
df = pd.read_csv("D:/mannu/ML/resume screener/dataset/Resume/Resume.csv")

In [50]:
df.head()

,ID,Resume_str,Resume_html,Category
0,16852973,HR ADMINISTRATOR/MARKETING ASSOCIATE\...,"<div class=""fontsize fontface vmargins hmargin...",HR
1,22323967,"HR SPECIALIST, US HR OPERATIONS ...","<div class=""fontsize fontface vmargins hmargin...",HR
2,33176873,HR DIRECTOR Summary Over 2...,"<div class=""fontsize fontface vmargins hmargin...",HR
3,27018550,HR SPECIALIST Summary Dedica...,"<div class=""fontsize fontface vmargins hmargin...",HR
4,17812897,HR MANAGER Skill Highlights ...,"<div class=""fontsize fontface vmargins hmargin...",HR

In [51]:
df.drop(columns=['ID', 'Resume_html'], axis=1, inplace=True)

In [52]:
df.head(5)

                                          Resume_str Category
0           HR ADMINISTRATOR/MARKETING ASSOCIATE\...       HR
1           HR SPECIALIST, US HR OPERATIONS      ...       HR
2           HR DIRECTOR       Summary      Over 2...       HR
3           HR SPECIALIST       Summary    Dedica...       HR
4           HR MANAGER         Skill Highlights  ...       HR

In [53]:
df["Resume_str"][0]

"         HR ADMINISTRATOR/MARKETING ASSOCIATE\n\nHR ADMINISTRATOR       Summary     Dedicated Customer Service Manager with 15+ years of experience in Hospitality and Customer Service Management.   Respected builder and leader of customer-focused teams; strives to instill a shared, enthusiastic commitment to customer service.         Highlights         Focused on customer satisfaction  Team management  Marketing savvy  Conflict resolution techniques     Training and development  Skilled multi-tasker  Client relations specialist           Accomplishments      Missouri DOT Supervisor Training Certification  Certified by IHG in Customer Loyalty and Marketing by Segment   Hilton Worldwide General Manager Training Certification  Accomplished Trainer for cross server hospitality systems such as    Hilton OnQ  ,   Micros    Opera PMS   , Fidelio    OPERA    Reservation System (ORS) ,   Holidex    Completed courses and seminars in customer service, sales strategies, inventory control, loss prevention, safety, time management, leadership and performance assessment.        Experience      HR Administrator/Marketing Associate\n\nHR Administrator     Dec 2013   to   Current      Company Name   －   City  ,   State     Helps to develop policies, directs and coordinates activities such as employment, compensation, labor relations, benefits, training, and employee services.  Prepares employee separation notices and related documentation  Keeps records of benefits plans participation such as insurance and pension plan, personnel transactions such as hires, promotions, transfers, performance reviews, and terminations, and employee statistics for government reporting.  Advises management in appropriate resolution of employee relations issues.  Administers benefits programs such as life, health, dental, insurance, pension plans, vacation, sick leave, leave of absence, and employee assistance.     Marketing Associate \xa0   Designed and created marketing collateral for sales meetings, trade shows and company executives.  Managed the in-house advertising program consisting of print and media collateral pieces.  Assisted in the complete design and launch of the company's website in 2 months.  Created an official company page on Facebook to facilitate interaction with customers.  Analyzed ratings and programming features of competitors to evaluate the effectiveness of marketing strategies.         Advanced Medical Claims Analyst     Mar 2012   to   Dec 2013      Company Name   －   City  ,   State     Reviewed medical bills for the accuracy of the treatments, tests, and hospital stays prior to sanctioning the claims.  Trained to interpret the codes (ICD-9, CPT) and terminology commonly used in medical billing to fully understand the paperwork that is submitted by healthcare providers.  Required to have organizational and analytical skills as well as computer skills, knowledge of medical terminology and procedures, statistics, billing standards, data analysis and laws regarding medical billing.         Assistant General Manager     Jun 2010   to   Dec 2010      Company Name   －   City  ,   State     Performed duties including but not limited to, budgeting and financial management, accounting, human resources, payroll and purchasing.  Established and maintained close working relationships with all departments of the hotel to ensure maximum operation, productivity, morale and guest service.  Handled daily operations and reported directly to the corporate office.  Hired and trained staff on overall objectives and goals with an emphasis on high customer service.  Marketing and Advertising, working on public relations with the media, government and local businesses and Chamber of Commerce.         Executive Support / Marketing Assistant     Jul 2007   to   Jun 2010      Company Name   －   City  ,   State     Provided assistance to various department heads - Executive, Marketing, Customer Service, Human Resources.  Managed front-end operations to ensure friendly and efficient transactions.  Ensured the swift resolution of customer issues to preserve customer loyalty while complying with company policies.  Exemplified the second-to-none customer service delivery in all interactions with customers and potential clients.         Reservation & Front Office Manager     Jun 2004   to   Jul 2007      Company Name   －   City  ,   State          Owner/ Partner     Dec 2001   to   May 2004      Company Name   －   City  ,   State          Price Integrity Coordinator     Aug 1999   to   Dec 2001      Company Name   －   City  ,   State          Education      N/A  ,   Business Administration   1999     Jefferson College   －   City  ,   State       Business Administration  Marketing / Advertising         High School Diploma  ,   College Prep. studies   1998     Sainte Genevieve Senior High   －   City  ,   State       Awarded American Shrubel Leadership Scholarship to Jefferson College         Skills     Accounting, ads, advertising, analytical skills, benefits, billing, budgeting, clients, Customer Service, data analysis, delivery, documentation, employee relations, financial management, government relations, Human Resources, insurance, labor relations, layout, Marketing, marketing collateral, medical billing, medical terminology, office, organizational, payroll, performance reviews, personnel, policies, posters, presentations, public relations, purchasing, reporting, statistics, website.    "

In [54]:
df["Category"].value_counts()

Category
INFORMATION-TECHNOLOGY    120
BUSINESS-DEVELOPMENT      120
ADVOCATE                  118
CHEF                      118
ENGINEERING               118
ACCOUNTANT                118
FINANCE                   118
FITNESS                   117
AVIATION                  117
SALES                     116
BANKING                   115
HEALTHCARE                115
CONSULTANT                115
CONSTRUCTION              112
PUBLIC-RELATIONS          111
HR                        110
DESIGNER                  107
ARTS                      103
TEACHER                   102
APPAREL                    97
DIGITAL-MEDIA              96
AGRICULTURE                63
AUTOMOBILE                 36
BPO                        22
Name: count, dtype: int64

In [55]:
df.shape

(2484, 2)

In [56]:
new_df = df[df["Category"]=='INFORMATION-TECHNOLOGY']

In [57]:
new_df.shape

(120, 2)

In [58]:
new_df.reset_index(drop=True, inplace=True)

In [59]:
new_df.sample(5)

                                           Resume_str                Category
50           DIRECTOR OF INFORMATION TECHNOLOGY   ...  INFORMATION-TECHNOLOGY
41           INFORMATION TECHNOLOGY SPECIALIST    ...  INFORMATION-TECHNOLOGY
26           DIRECTOR OF INFORMATION TECHNOLOGY   ...  INFORMATION-TECHNOLOGY
15           INFORMATION TECHNOLOGY SPECIALIST    ...  INFORMATION-TECHNOLOGY
63           INFORMATION TECHNOLOGY COORDINATOR   ...  INFORMATION-TECHNOLOGY

In [60]:
stop_words = set(stopwords.words('english'))

PROTECTED_WORDS = {
    'it', 'ms', 'sql', 'aws', 'ai', 'ml', 'ui', 'ux',
    'c', 'c++', 'c#'
}

def transform_text(text):
    text = re.sub('[^a-zA-Z0-9]+#', ' ',text)

    text = text.lower()
    
    words = text.split()

    cleaned_words = []
    for word in words:
        if word in PROTECTED_WORDS:
            cleaned_words.append(word)
            continue
        
        if word in stop_words:
            continue
        if len(word) <= 2 and word not in ['ai', 'ml', 'ms']:
            continue
        cleaned_words.append(lemmatizer.lemmatize(word))
    
    return ' '.join(cleaned_words)

In [61]:
new_df["clean_resume"]= new_df["Resume_str"].apply(transform_text)

In [62]:
new_df["clean_resume"]

0      information technology summary dedicated infor...
1      information technology specialist gs11 experie...
2      information technology supervisor summary seek...
3      information technology instructor summary seve...
4      information technology manager/analyst profess...
                             ...
115    corporate project manager career overview seas...
116    it technology specialist professional summary ...
117    it manager highlight customer client relation ...
118    subject matter expert (information technology ...
119    training manager executive summary qualified t...
Name: clean_resume, Length: 120, dtype: object

In [63]:
original_text = new_df["Resume_str"].iloc[0]

In [64]:
transform__text = new_df["clean_resume"].iloc[0]

In [65]:
print(original_text[:900])
print(transform__text[:900])

         INFORMATION TECHNOLOGY         Summary     Dedicated  Information Assurance Professional  well-versed in analyzing and mitigating risk and finding cost-effective solutions. Excels at boosting performance and productivity by establishing realistic goals and enforcing deadlines.  Versatile IT professional with 37 years of Enterprise design and engineering methodology.       Skills          Enterprise platforms  Knowledge of Product Lifecycle Management (PLM)  Project tracking  Hardware and software upgrade planning  Product requirements documentation  Self-directed  MS Visio  Decisive  Collaborative  Domain Active Directory Layout  Data storage engineering      Information Assurance  Risk Management Framework (RMF)  Active Directory design and deployment  Workstation build and deployment  Systems Accreditation Packages  Red Hat Enterprise Linux installation and hardening  Network
information technology summary dedicated information assurance professional well-versed analyzing mitigating risk finding cost-effective solutions. excels boosting performance productivity establishing realistic goal enforcing deadlines. versatile it professional year enterprise design engineering methodology. skill enterprise platform knowledge product lifecycle management (plm) project tracking hardware software upgrade planning product requirement documentation self-directed ms visio decisive collaborative domain active directory layout data storage engineering information assurance risk management framework (rmf) active directory design deployment workstation build deployment system accreditation package red hat enterprise linux installation hardening network design troubleshooting high performance computing experience company name city state information technology 02/2011 current hi

# Tf -IDF encoding

In [66]:
corpus = new_df["clean_resume"].tolist()

job_description = """
We are hiring an Information Technology Engineer responsible for designing,
developing, and maintaining software systems. The candidate should have strong
experience in python programming, sql databases, data structures and algorithms,
and rest api development. Hands-on experience with linux, git version control,
and cloud platforms such as aws is required. Familiarity with system design,
debugging, and basic networking concepts is a plus.
"""

In [67]:
corpus

["information technology summary dedicated information assurance professional well-versed analyzing mitigating risk finding cost-effective solutions. excels boosting performance productivity establishing realistic goal enforcing deadlines. versatile it professional year enterprise design engineering methodology. skill enterprise platform knowledge product lifecycle management (plm) project tracking hardware software upgrade planning product requirement documentation self-directed ms visio decisive collaborative domain active directory layout data storage engineering information assurance risk management framework (rmf) active directory design deployment workstation build deployment system accreditation package red hat enterprise linux installation hardening network design troubleshooting high performance computing experience company name city state information technology 02/2011 current hired manage accreditation effort major department modernization project involving accreditation package leading successful authorization operate decisions. responsibility increased include departmental accreditation effort leading another successful atos. now, working new accreditation including re-authorization existing project. succeeded writing implementing vulnerability management existing accredited systems. success accreditation hinged coordination oni enterprise critical design decision help program integrate smoothly enterprise thru many meetings, analyzing enterprise business model understand best fit program. different project required careful management specific stig compliance hardening different configuration service required specific domain integrated. analyzed complex computer system assess vulnerability risk. supervised external computer consultant vendors. managed application patches, data backup, security change network configuration. company name city state system engineer 02/2006 02/2011 hired initiate processing strategy fulfilling department analyst requirements. requirement fulfilled thru dentifying product problem strength collected data customer experience review enterprise compliance transition new technology supporting new processing need thru proper processing power. next challenge came storage requirement better performance controlled uses. careful study local infrastructure design, local storage shelf solution adopted grow local storage 200tb. using solution, department saved million dollar purchasing maintenance cost compared alternative. next came requirement improve processing future big data format fulfilled red hat linux high compute cluster designed, purchased accredited operation enterprise. improvement big data analytical processing reduced time hour minute well allow robust data thru higher selection sensors, frequency range allowed thru traditional process. company name city state senior system analyst 02/1999 02/2006 hired improve corporate client communication processing requirement resulted design, build deployment enterprise network solutions. one solution resulted expanding capability supporting washington navy yard, norfolk virginia hawaii support facilities. fulfilled requirement detecting crucial network software/hardware weakness developing preventive strategy solution avoiding interruption increasing system security thru documenting system layouts, wiring diagram addressing schema understand layout make informed solution upper management. education training associate science electronic engineering 1980 florence darlington technical school city state electronic engineering. dean's list high gpa. class president second year skill active directory hardware engineering information technology red hat enterprise linux server ms window server ms window desktop network design troubleshooting architectural diagram accreditation boundary risk management enterprise strategy vendor relation desktop publishing software: photoshop, illustrator, html team work collaboration",
 "information technology specialist gs11 experience 07/2004 current information technology specialist gs11 company name city state information technology specialist; supervison; project management; circuit management; licensed electrician; alarm management; alarm technician; training; supply; quality assurance kevin trostle, dsn 266-4800, comm. 865) 336-4800 manage assigned it/communications environment privileged access network level wing, geographically separated unit (gsu), tenants. plan, coordinate, install, continuously analyze system design, hardware software. develop, recommend, install solution upgrade ensure availability, integrity, efficiency, reliability component assigned system. ensure performed work captured remedy ticketing system. manage telecommunication nipr network wing, gsu's, tenant units. continually plan, install, analyze new hardware, software process ensure network reliable efficient. serve focal point ensuring functionality operability assigned it/data systems/functions, voice, wireless system support mission requirements. optimize, analyze, manage, direct installation new hardware software introduced environment ensure compatibility existing architecture, reliability, functionality relation organization's business requirements. oversee initiate corrective preventative measure rectify immediate problem prevent future occurrence cfp. troubleshoot diagnose system failure isolate source problems. provide customer technical assistance/support users. provide management information necessary address difficult/complex problems. review purchase requests, sow's ensuring documentation sufficient justify enhancement keep system current. work cfp/customers resolve integration configuration related issues. ensure upgrade base it infrastructure identified. assist customer developing/submitting recommendation equipment funds. assist personnel planning/developing new additional infrastructure/architecture capabilities. coordinate effort system customers, support personnel, commercial vendor identify/resolve system anomalies. conduct feasibility study identify analyze system failure analyzes data determine trend exist forecast need future replacement modification system hardware software. budget constraint dictate, evaluates alternative mean satisfying user requirement provides management technically feasible cost efficient approach meet changing needs. keep abreast change technology assist management preparing future enhancements. 02/2001 current cyber transport/ client system workcenter supervisor company name city state kevin trostle, dsn 266-4800, comm. 865) 336-4800 manage cyber transport/client system work center personnel. set adjust work priorities, evaluate, counsel subordinates. document training personnel using computer based training system (tba) sustain operate system effective troubleshooting, repair, pmi's, system performance testing/analysis. system include network infrastructure equipment, cabling, voice systems, video systems, small computers, printer maintain close working relationship communication focal point--production requirements/remedy tickets. 07/1996 07/2000 f-16 ejection system technician company name city state ronald buckman, comm. 803) 895-1190 troubleshot, removed, tested, inspected, repaired, modified, installed explosive non-explosive component assembly ejection systems. performed preventative maintenance ninety different electronically fired explosive device ensuring proper wiring termination. foreign object damage monitor, briefed wing commander monthly findings. ran entire supply system ensuring part supply readily available. hazardous material monitor. explosive inspector. ensured proper grounding point present shop prevent electrostatic discharge explosive components. section workgroup manager charge maintaining computer ensured needed software installed. shop computer security monitor. trained supervised personnel. quality assurance assessor. education training jun 1996 diploma general study brockport high school city state general study may 2003 degree electrical engineering university city state electrical engineering november 1996 usaf, electronic principles, june 2002 august 2002; usaf, telephone system apprentice course, september 2002 december 2002; usaf, aircrew egress system apprentice course numerous certificate web-based training lan fundamentals, routers, topologies, cisco networking, etc. interest stationed south carolina performed three year volunteer electrical work habitat humanity. work learned fundamental wiring house electric, cable, telephone. skill budget, cabling, cisco, hardware, client, documentation, electrician, feasibility studies, funds, information technology, inspector, lan, materials, access, network, networking, networks, personnel, telephone systems, printers, processes, project management, quality assurance, routers, system design, technical assistance, technician, telecommunications, troubleshoot, troubleshooting, upgrades, video, wiring additional information awards: superior performer, 2nd quarter 2003; usaf achievement medal, june 2000; humanitarian service medal, january 1998; cr maintenance professional year, 1998; airman quarter, may 1997; airman month, march 1997; airman month, february 1997 information: stationed south carolina performed three year volunteer electrical work habitat humanity. work learned fundamental wiring house electric, cable, telephone.",
 'information technology supervisor summary seeking position information technology specialist. year information technology experience u.s. army, including year supervisory experience. trained personnel set-up it equipment, ensuring equipment properly connected functioning. regularly troubleshoot install various it equipment systems. accountable maintenance inventory million worth it communication equipment zero loss damages. possess security microsoft certification secret security clearance. highlight excellent communication technique manufacturing system integration multidisciplinary exposure design instruction creation project management complex problem solver advanced critical thinking sharepoint microsoft excel, project visio accomplishment army achievement medal impacting communication network overall success key resolve yong san, korea. air force achievement medal supporting operation iraqi freedom performing outstanding senior controller. certificate achievement outstanding support member tiger team window migration. good conduct medal exemplary behavior, efficiency fidelity active federal military service. experience information technology supervisor 01/2011 05/2014 company name city state supervise personnel one time, delegating tasks, conducting performance evaluation providing corrective counseling necessary. train personnel set-up proper use it related equipment adhering policy procedures. responsible inventory million worth network communication equipment. tasked president united state act supervisor maintain signal communication fort bragg army base. information technology technician 01/2009 01/2011 company name city state maintained communication equipment order effectively relay confidential secret information. utilized electronic test equipment troubleshoot malfunctioning communication equipment complete repair necessary. regularly set added computer system communication network, installing operation systems, accessing stored program utilizing addresses. received training lan/wan protocols. radiology technologist 05/2008 09/2008 company name city state routinely performed radiological examination medical clinic. competent experienced set-up adjustment medical device equipment. regularly provided customer assistance, ensuring patient received timely accurate care. accountable accurate documentation via electronic database file system ensuring confidentiality maintained. command post controller 10/2001 10/2005 company name city state provided command, control, communications, information support throughout operation peacetime, emergency, disaster situations. received relayed instruction records, submitting manual automated data products. disseminated time-sensitive critical information senior leader support agencies. education certification, window microsoft, fort bragg, nc, 2012 *certification, security comptia, yong san, korea, 2012 *distinguished graduate certificate, information technology (network communications) course 2009 u.s. army city state certificate, it network cisco routing, it field service branch 2009 city state associate science radiography 2008 northwest florida state college city state radiography certificate 2001 it tech prep, trumbull career technical center state diploma 2001 warren harding city state skill army, cisco, counseling, customer assistance, database, documentation, information technology, inventory, ip, lan, window network, personnel, policies, protocols, repairs, routing, san, supervisor, test equipment, troubleshoot, wan',
 "information technology instructor summary seventeen year experience information technology field. seven year experience curriculum design computer based training development. group project management experience twelve years. advanced problem solving skill expertise. advanced customer service training experience curriculum data analysis curriculum design advanced data analysis student counseling learning analysis market analysis customer service training advanced planning training success evaluation team building articulation development quantitative project analysis project management implementation qualitative project analysis advanced conflict resolution evaluation advanced user experience market driven planning expertise computer based training design data analysis highlight medium design productivity photoshop microsoft network management premier word novell console illustrator excel microsoft networking indesign powerpoint cable wiring standard flash project machine hardware dreamweaver outlook window installation firework ilife repair soundbooth page mac installation repair quarkxpress number virtualization camtasia keynote parallells html coding imovie vmware, desktop fusion php database connection iphoto course management software experience information technology instructor ................................................................................................................... jan 2012 current company name city state manage student learning needs. create curriculum it program. manage two part time instructors. teach three class twenty-two student class per day. manage open entry/open exit curriculum training program. verify training outcome report maintain coe standards. data metric analysis student progress throughout course. answer question potential student parents. review update training standard needed. new curriculum development according market requirement customer service training tailored towards it student partner fellow instructor provide cross training student interaction work student service assure student success counsel student learning method method improvement. help desk manager campus ..................................................................................................................... jan 2010 jan 2012 company name city state manage incoming troubleshooting call four state agencies. assisted help desk staff member resolving customer request first call resolution. create specify computer standard utah dept. health. trained fourteen help desk staff member help desk phone client installation usage. software management dept. health. manage new user creation procedure state department health natural resources. created new user training documentation thirty help desk staff member state utah. provide remote control support customer throughout state. customer friendliness reported several occasion management staff, commended ability teach customer utilize technology effectively. medium designer .................................................................................................................................................. jan 2009 jan 2010 company name city state prepare training curriculum preparedness trainings. designed eighteen computer based training course department health's management staff training one hundred manager providing significant cost savings. coordinated information technology need fifty preparedness staff members. designed cover art multimedia presentation give trainee sessions, prepared one thousand take home packet various trainings. served technical lead staff member utah department health's training education center. technical support specialist ............................................................................................................................ jan 2002 jan 2009 company name city state provided advanced level technical support department staff computer repair service. inventory control department health hardware. created technology standard division health system improvement. served advisory committee mobile device policy creation. updated department travel system paper online. education master education learning technology 2012 doctorate education; higher education, ed.d ...........................concordia university m.ed. ............................. western governor's university learning technology bachelor science information technology management information technology management b.s. ......... 2010 western governor's university associate applied science multimedia technology multimedia technology a.a.s ......................... 2003 utah valley university skill photoshop, premier, art, cable, hardware, computer repair, curriculum development, client, customer service training, database, department health, documentation, dreamweaver, fireworks, flash, help desk, html coding, illustrator, indesign, information technology, inventory control, mac os, market, excel, microsoft networking, outlook, powerpoint, window os, word, multimedia presentations, natural, network management, novell, php, progress, quarkxpress, staff training, technical support, user training, phone, troubleshooting, wiring",

In [80]:
def rank_resumes(clean_resumes, clean_jd, top_n=5):
    Tfidf = TfidfVectorizer(
        max_features=3000,
        ngram_range = (1,2)
    )

    resume_vectors = Tfidf.fit_transform(corpus)

    jd_vector = Tfidf.transform([job_description])

    similarity_score = cosine_similarity(jd_vector, resume_vectors).flatten()
    top_indices = np.argsort(scores)[::-1][:top_n]

    return top_indices, similarity_score

## Rank resumes

In [ ]:
# scores = similarity_score.flatten() # convert 2D into 1D 
# top_indices = np.argsort(scores)[::-1][:5] # 1. asencending order and return descending and take top 5 indices

# for i in top_indices:
#     print(f"Score: {scores[i]:.3f}")
#     print(df.iloc[i]['Resume_str'][:200])
#     print("------")

Score: 0.119
         FIELD HR ASSOCIATE           Summary    Reliable HR Field Associate with a Master's of science in Human Resource management emphasis as a Generalist. Passionate and motivated with a drive for
------
Score: 0.102
         GRAPHIC DESIGNER           Summary    Enthusiastic student majoring in Chemistry; great at performing many task in a timely matter and as efficient as possible. Strong background in computer
------
Score: 0.101
         E-LEARNING DESIGNER           Career Overview    Highly skilled and experienced educator with a strong
background in information technology. Adept at addressing the needs of a variety of lear
------
Score: 0.097
         HR SERVICES REPRESENTATIVE       Summary     A multi-skilled professional with good all-round HR imformatory skills. Very capable with an ability deal with all the recruitment/processing need
------
Score: 0.095
         DESIGNER / TECHNICAL DESIGNER           Summary     Creative fashion designer with background in the catagories of swim, intimate apparel, loungewear, and sportswear.  Experience designing wo
------

“I computed cosine similarity between the job description vector and all resume vectors, then sorted the scores to retrieve the top matching candidates.”

## -> Skill gap analysis

In [73]:
SKILLS = {
    "python", "java", "sql", "aws", "linux", "git",
    "rest api", "api", "docker", "kubernetes",
    "data structures", "algorithms",
    "system design", "networking"
}

clean_jd = transform_text(job_description)

In [74]:
def extract_skills(text, skills):
    found_skills = set()
    for skill in SKILLS:
        if skill in text:
            found_skills.add(skill)
    return found_skills

In [75]:
jd_skills = extract_skills(clean_jd, SKILLS)
print("JD skills:" , jd_skills)

JD skills: {'api', 'networking', 'sql', 'linux', 'aws', 'algorithms', 'system design', 'git', 'python', 'rest api'}

In [76]:
resume_text = new_df.iloc[top_indices[0]]["clean_resume"]
resume_skills = extract_skills(resume_text, SKILLS)

missing_skills = jd_skills - resume_skills

print("Resume skills :" , resume_skills)
print("missing skills :" , missing_skills)

Resume skills : {'aws', 'networking', 'python', 'linux'}
missing skills : {'api', 'sql', 'algorithms', 'system design', 'git', 'rest api'}

combining ranking + skill gap

In [78]:
display_socre = scores * 100

In [79]:
for i in top_indices[:3]:
    resume_text = new_df.iloc[i]['clean_resume']
    resume_skills = extract_skills(resume_text, SKILLS)
    missing = jd_skills - resume_skills

    print(f"Score: {display_socre[i]:.3f}")
    print("missing skills: ", missing)
    print("---------------------------")

Score: 11.950
missing skills:  {'api', 'sql', 'algorithms', 'system design', 'git', 'rest api'}
---------------------------
Score: 10.199
missing skills:  {'api', 'sql', 'aws', 'algorithms', 'system design', 'git', 'python', 'rest api'}
---------------------------
Score: 10.054
missing skills:  {'api', 'sql', 'linux', 'aws', 'algorithms', 'system design', 'git', 'rest api'}
---------------------------

Typical ranges in real text systems:

0.00 – 5 → almost no match

5 – 12 → weak but relevant match

12 – 25 → decent match

< 30 → very strong (rare in resumes)

format & normalize output

In [81]:
def get_skill_gap(jd_skills, resume_skills):
    """
    return skills missing in resume compare to jd
    """
    return jd_skills - rresume_skillse